#!/usr/bin/env python3

import gam_gate as gam
import gam_g4 as g4
import click

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])


@click.command(context_settings=CONTEXT_SETTINGS)
@click.option('--short/--not-short', '-s',
              default=False,
              help='If true, display Gate path only')
def gt_gate_info(short):
    """
    Print information about a Gam-Gate and the environment
    """

    gi = g4.GamInfo
    v = gi.get_G4Version().replace('$Name: ', '')
    v = v.replace('$', '')

    print(f'Geant4 version {v}')
    print(f'Geant4 MT ?    {gi.get_G4MULTITHREADED()}')
    print(f'Geant4 date    {gi.get_G4Date()}')
    print(f'ITK version    {gi.get_ITKVersion()}')


if __name__ == '__main__':
    gt_gate_info()
