
/control/execute mac/verbose.mac

#/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 2 m
/gate/world/geometry/setYLength 2 m
/gate/world/geometry/setZLength 2 m
/gate/world/setMaterial G4_AIR

/control/execute mac/spect_head.mac

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 0.01 mm
/gate/physics/Electron/SetCutInRegion   world 0.01 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm
/gate/physics/Proton/SetCutInRegion     world 1 mm

/gate/physics/displayCuts


#=====================================================
# OUTPUT
#=====================================================

/gate/actor/addActor              SimulationStatisticActor stat
/gate/actor/stat/save             output/stat.txt

/control/execute mac/output.mac

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize


#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource mybeam1 gps
/gate/source/mybeam1/setActivity 2000 Bq
/gate/source/mybeam1/gps/particle gamma
/gate/source/mybeam1/gps/ene/mono 140.5 keV
/gate/source/mybeam1/gps/pos/type Volume
/gate/source/mybeam1/gps/pos/shape Sphere
/gate/source/mybeam1/gps/pos/radius 4 cm
/gate/source/mybeam1/gps/pos/centre 0 0 -15 cm
/gate/source/mybeam1/gps/direction 0 0 1

#=====================================================
# START BEAMS
#=====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/run/verbose 1
# /gate/random/verbose 1
# /gate/source/verbose 0

# to check Steplimiter
# /tracking/verbose 1

/gate/application/setTimeStart 0 s
/gate/application/setTimeSlice 1 s
/gate/application/setTimeStop  1 s
/gate/application/startDAQ

