
# Digitizer for Technetium-99m
# Primary window: 20% centered around 140.5 keV
# Secondary window: 10% centered around 120 keV

# Adder
/gate/digitizer/Singles/insert adder

# Readout
/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setPolicy TakeEnergyCentroid
/gate/digitizer/Singles/readout/setDepth 1


# Intrinsic Spatial Blurring
#/gate/digitizer/Singles/insert spblurring
#/gate/digitizer/Singles/spblurring/setSpresolution 4.37 mm
#/gate/digitizer/Singles/spblurring/verbose 0

# Energy Blurring
#/gate/digitizer/Singles/insert blurring
#/gate/digitizer/Singles/blurring/setLaw linear
#/gate/digitizer/Singles/blurring/linear/setResolution 0.1
#/gate/digitizer/Singles/blurring/linear/setEnergyOfReference 171.0 keV
#/gate/digitizer/Singles/blurring/linear/setEnergyOfReference 140.5 keV
#/gate/digitizer/Singles/blurring/linear/setSlope -0.0194 1/MeV

# Thresholds Tc99m
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 3. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 515. keV

# Scatter Windows
/gate/digitizer/name scatter
/gate/digitizer/insert singleChain
/gate/digitizer/scatter/setInputName Singles
/gate/digitizer/scatter/insert thresholder
/gate/digitizer/scatter/thresholder/setThreshold 114. keV
/gate/digitizer/scatter/insert upholder
/gate/digitizer/scatter/upholder/setUphold 126. keV

# Tc-99m : 140.5 keV windows, width of 20%
/gate/digitizer/name peak140
/gate/digitizer/insert singleChain
/gate/digitizer/peak140/setInputName Singles
/gate/digitizer/peak140/insert thresholder
/gate/digitizer/peak140/thresholder/setThreshold 126.45 keV
/gate/digitizer/peak140/insert upholder
/gate/digitizer/peak140/upholder/setUphold 154.55 keV

# total spectrum
#/gate/digitizer/name spectrum
#/gate/digitizer/insert singleChain
#/gate/digitizer/spectrum/setInputName Singles
#/gate/digitizer/spectrum/insert thresholder
#/gate/digitizer/spectrum/thresholder/setThreshold 3. keV
#/gate/digitizer/spectrum/insert upholder
#/gate/digitizer/spectrum/upholder/setUphold 515. keV

