import pandas as pd
import uproot
import numpy as np

from enum import Enum, auto


class DeadTimePolicy(Enum):
    NonParalyzable = auto()
    Paralyzable = auto()


def deadtime(
    singles_before_deadtime: pd.DataFrame,
    dead_time: float,
    policy: DeadTimePolicy = DeadTimePolicy.NonParalyzable,
) -> dict:
    """
    This function simulates dead time (given in ns).
    The singles_before_deadtime are in a pandas DataFrame.
    It returns a dict in which the keys are volume IDs, and the values are a pandas DataFrame
    representing the singles for that volume ID after dead time.
    """
    df = singles_before_deadtime  # df for DataFrame
    grouped = df.groupby("PreStepUniqueVolumeID")

    singles_after_deadtime = {}
    for volume_id, group in grouped:
        # For each volume, start with a sorted list of singles time values in ns.
        group = group.sort_values("GlobalTime")
        times = group["GlobalTime"].values

        if len(times) == 0:
            continue

        next_single = 0
        while next_single < len(times):
            current = next_single  # index of a single that opens the current dead time interval
            next_single = current + 1
            begin = times[current]
            singles_after_deadtime.setdefault(volume_id, []).append(group.iloc[current])
            # Increment next until it points to the single that opens the next dead time interval.
            while next_single < len(times) and times[next_single] <= begin + dead_time:
                if policy == DeadTimePolicy.Paralyzable:
                    begin = times[next_single]
                next_single += 1

    return singles_after_deadtime


def check_gate_deadtime(
    root_file_path: str,
    name_before_deadtime: str,
    name_after_deadtime: str,
    dead_time: float,
    policy: DeadTimePolicy,
):
    """
    This function checks that the singles generated by GateDigitizerDeadTimeActor are identical
    to the ones generated by the Python dead time implementation in the deadtime() function above.
    """
    with uproot.open(root_file_path) as root_file:
        singles_before_deadtime = root_file[name_before_deadtime].arrays(library="pd")
        actual_singles_after_deadtime = root_file[name_after_deadtime].arrays(
            library="pd"
        )

    expected_singles_after_deadtime = deadtime(
        singles_before_deadtime,
        dead_time,
        policy,
    )
    num_expected_singles = sum(
        len(entries) for entries in expected_singles_after_deadtime.values()
    )

    print(f"Singles before dead time: {len(singles_before_deadtime)}")
    print(
        f"Expected singles after dead time: {num_expected_singles} ({num_expected_singles / len(singles_before_deadtime) * 100:.01f}%)"
    )
    print(f"Actual singles after dead time: {len(actual_singles_after_deadtime)}")

    all_match = True
    for volume_id in expected_singles_after_deadtime.keys():

        # Get the expected singles (Python) and actual singles (GateDigitizerDeadTimeActor) for the current volume.
        expected_singles = pd.DataFrame(expected_singles_after_deadtime[volume_id])
        actual_singles = (
            actual_singles_after_deadtime[
                actual_singles_after_deadtime["PreStepUniqueVolumeID"] == volume_id
            ]
            .sort_values("GlobalTime")
            .reset_index(drop=True)
        )

        # Compare the number of singles
        if len(expected_singles) != len(actual_singles):
            print(
                f"Volume {volume_id}: Expected {len(expected_singles)} singles, got {len(actual_singles)}"
            )
            all_match = False
            continue

        # Compare all attributes, except the volume ID
        for attr in expected_singles.columns:
            if attr == "PreStepUniqueVolumeID":
                continue
            expected_values = expected_singles[attr].values
            actual_values = actual_singles[attr].values
            if np.issubdtype(expected_values.dtype, np.floating):
                if not np.allclose(expected_values, actual_values, rtol=1e-9):
                    print(f"Volume {volume_id}: Attribute {attr} does not match")
                    mismatch_indices = np.where(
                        ~np.isclose(expected_values, actual_values, rtol=1e-9)
                    )[0]
                    first_mismatch_idx = mismatch_indices[0]
                    print(
                        f"  Single index {first_mismatch_idx}: expected={expected_values[first_mismatch_idx]}, actual={actual_values[first_mismatch_idx]}"
                    )
                    all_match = False
                    break
            else:
                if not all(expected_values == actual_values):
                    print(f"Volume {volume_id}: Attribute {attr} does not match")
                    mismatch_indices = np.where(expected_values != actual_values)[0]
                    first_mismatch_idx = mismatch_indices[0]
                    print(
                        f"  Single index {first_mismatch_idx}: expected={expected_values[first_mismatch_idx]}, actual={actual_values[first_mismatch_idx]}"
                    )
                    all_match = False
                    break

    return all_match
