#!/bin/bash
set -ex

# apt.txt: install libGL for opengate_core wheel

#install opengate and opengate_core
cd
pip install --verbose -e .

#create the notebooks from tests
pip install p2j
mkdir notebook
cp -r opengate/tests/* notebook/
cd notebook
mkdir notebook
rm -rf __init__.py readme.md opengate_tests*
cd src
files=`ls test*.py`
for file in $files
do
    sed -i 's/__file__/pathlib.Path(globals()["_dh"][0]) \/ "__init__.py"/' $file
    p2j $file
done
mv *.ipynb ../notebook
cd ..
rm -rf src

