#!/bin/bash
set -ex

# apt.txt: install libGL for gam_g4 wheel

#install gam_gate and gam_g4
cd
pip install --verbose -e .

#create the notebooks from gam_tests
pip install p2j
mkdir notebook
cp -r gam_tests/* notebook/
cd notebook
mkdir notebook
rm -rf __init__.py readme.md gam_gate_tests* 
cd src
files=`ls test*.py`
for file in $files
do
    p2j $file
done
mv *.ipynb ../notebook
cd ..
rm -rf src

