#Docker for opengate_core
#systemctl start docker
#login: docker login
#build: docker build -t tbaudier/opengate_core -f Dockerfile_opengate_core_arm64 .
#push: docker push tbaudier/opengate_core
#run: docker run --rm -e "PYTHONFOLDER=${PYTHONFOLDERMANYLINUX}" -v $(Pipeline.Workspace)/software:/home tbaudier/opengate_core /home/opengate_core/azureCreateWheelLinux.sh
#interactive: docker run -ti --rm -v $PWD:/home quay.io/pypa/manylinux_2_34_aarch64 /bin/bash
#with arm64 on x86 machines: use qemu and run
#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#docker build --platform linux/arm64 -t tbaudier/opengate_core -f Dockerfile_opengate_core_arm64 .

FROM quay.io/pypa/manylinux_2_34_aarch64
MAINTAINER Thomas Baudier <thomas.baudier@creatis.insa-lyon.fr>
#Install packages
RUN     yum install -y gcc wget git expat-devel fftw-devel qt6-qtbase-devel freeglut-devel libXmu-devel xerces-c-devel \

#Create folder
    &&  mkdir -p /software/cmake /software/geant4/src /software/geant4/bin /software/itk/src /software/itk/bin /software/wheelhouse \

#Install cmake
    &&  cd /software/cmake \
    &&  wget https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-linux-aarch64.tar.gz \
    &&  tar xzvf cmake-3.31.8-linux-aarch64.tar.gz \
    &&  rm -rf cmake-3.31.8-linux-aarch64.tar.gz \
    &&  mv cmake-3.31.8-linux-aarch64 cmake \
    &&  export PATH=/software/cmake/cmake/bin/:${PATH} \

#Compile Geant4
    &&  cd /software/geant4 \
    &&  git clone --branch v11.3.2 https://github.com/Geant4/geant4.git --depth 1 src \
    &&  cd bin \
    && . /opt/rh/gcc-toolset-14/enable \
    &&  cmake -DCMAKE_CXX_FLAGS=-std=c++17 -DGEANT4_BUILD_MULTITHREADED=ON -DGEANT4_USE_GDML=ON -DGEANT4_INSTALL_DATA=OFF -DGEANT4_USE_QT=ON -DGEANT4_USE_OPENGL_X11=ON -DGEANT4_USE_QT_QT6=ON -DGEANT4_BUILD_TLS_MODEL=global-dynamic ../src \
    &&  make -j10 \
    &&  source /software/geant4/bin/geant4make.sh \

#Compile ITK
    &&  cd /software/itk \
    &&  git clone --branch v5.4.4 https://github.com/InsightSoftwareConsortium/ITK.git --depth 1 src \
    &&  cd bin \
    && . /opt/rh/gcc-toolset-14/enable \
    &&  cmake -DCMAKE_CXX_FLAGS=-std=c++17 -DBUILD_TESTING=OFF -DITK_USE_FFTWD=ON -DITK_USE_FFTWF=ON -DITK_USE_SYSTEM_FFTW:BOOL=ON ../src \
    &&  make -j10
