FROM dockurr/windows:5.14

ENV VERSION=2025
ENV GEANT4_VERSION=geant4.11.0
ENV ITK_VERSION=v5.4.4

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install Miniconda
RUN Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile miniconda.exe ; `
    Start-Process .\miniconda.exe -ArgumentList '/S','/D=C:\Miniconda3' -Wait ; `
    Remove-Item miniconda.exe ; `
    C:\Miniconda3\Scripts\conda.exe create -n opengate_core python=3.11 -y ; `
    C:\Miniconda3\Scripts\conda.exe install -n opengate_core cmake=3.31.2 openssl=3.0.19 aqtinstall -y

# Install Qt6 (via aqt)
RUN New-Item -ItemType Directory -Force -Path $env:USERPROFILE\software | Out-Null ; `
    C:\Miniconda3\Scripts\conda.exe run -n opengate_core `
    python -m aqt install-qt windows desktop 6.10.2 win64_msvc2019_64 `
    --outputdir $env:USERPROFILE\software\qt6

# Install Geant4
RUN New-Item -ItemType Directory -Force -Path `
        $env:USERPROFILE\software\geant4\src, `
        $env:USERPROFILE\software\geant4\bin, `
        $env:USERPROFILE\software\geant4\data | Out-Null ; `
    Set-Location $env:USERPROFILE\software\geant4 ; `
    git clone --branch $env:GEANT4_VERSION https://github.com/Geant4/geant4.git --depth 1 src ; `
    Set-Location bin ; `
    C:\Miniconda3\Scripts\conda.exe run -n opengate_core cmake `
        -DGEANT4_INSTALL_DATA=ON `
        -DGEANT4_INSTALL_DATADIR=$env:USERPROFILE\software\geant4\data `
        -DGEANT4_BUILD_MULTITHREADED=ON `
        -DGEANT4_USE_QT=ON `
        -DGEANT4_USE_QT_QT6=ON `
        ..\src ; `
    C:\Miniconda3\Scripts\conda.exe run -n opengate_core cmake --build . --config Release

# Install ITK
RUN New-Item -ItemType Directory -Force -Path `
        $env:USERPROFILE\software\itk\src, `
        $env:USERPROFILE\software\itk\bin | Out-Null ; `
    Set-Location $env:USERPROFILE\software\itk ; `
    git clone --branch $env:ITK_VERSION https://github.com/InsightSoftwareConsortium/ITK.git --depth 1 src ; `
    Set-Location bin ; `
    C:\Miniconda3\Scripts\conda.exe run -n opengate_core cmake `
        -DCMAKE_CXX_FLAGS=-std=c++17 `
        -DBUILD_TESTING=OFF `
        ..\src ; `
    C:\Miniconda3\Scripts\conda.exe run -n opengate_core cmake --build . --config Release