#Docker for gam_g4
#systemctl start docker
#login: docker login
#build: docker build -t tbaudier/gam_g4 -f Dockerfile_gam_g4 .
#push: docker push tbaudier/gam_g4
#run: docker run --rm -e "PYTHONFOLDER=${PYTHONFOLDERMANYLINUX}" -v $(Pipeline.Workspace)/software:/home tbaudier/gam_g4 /home/gam_g4/azureCreateWheelLinux.sh
#interactive: docker run -ti --rm -v $(Pipeline.Workspace)/software:/home quay.io/pypa/manylinux2014_x86_64 /bin/bash

FROM quay.io/pypa/manylinux2014_x86_64
MAINTAINER Thomas Baudier <thomas.baudier@creatis.insa-lyon.fr>
#Install packages
RUN     yum install -y gcc wget git expat-devel fftw-devel qt5-qtbase-devel freeglut-devel libXmu-devel \

#Create folder
    &&  mkdir -p /software/cmake /software/geant4/src /software/geant4/bin /software/geant4/data /software/itk/src /software/itk/bin /software/wheelhouse \

#Install cmake
    &&  cd /software/cmake \
    &&  wget https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz \
    &&  tar xzvf cmake-3.18.2-Linux-x86_64.tar.gz \
    &&  export PATH=/software/cmake/cmake-3.18.2-Linux-x86_64/bin/:${PATH} \

#Compile Geant4
    &&  cd /software/geant4 \
    &&  git clone --branch v11.0.0 https://github.com/Geant4/geant4.git --depth 1 src \
    &&  cd bin \
    &&  cmake -DCMAKE_CXX_FLAGS=-std=c++17 -DGEANT4_BUILD_MULTITHREADED=ON -DGEANT4_INSTALL_DATA=ON -DGEANT4_INSTALL_DATADIR=/sofware/geant4/data -DGEANT4_USE_QT=ON -DGEANT4_USE_OPENGL_X11=ON ../src \
    &&  make -j10 \
    &&  source /software/geant4/bin/geant4make.sh \

#Compile ITK
    &&  cd /software/itk \
    &&  git clone --branch v5.1.0 https://github.com/InsightSoftwareConsortium/ITK.git --depth 1 src \
    &&  cd bin \
    &&  cmake -DCMAKE_CXX_FLAGS=-std=c++17 -DBUILD_TESTING=OFF -DITK_USE_FFTWD=ON -DITK_USE_FFTWF=ON -DITK_USE_SYSTEM_FFTW:BOOL=ON ../src \
    &&  make -j10

