FROM dockurr/macos:5.14

ENV VERSION=15
ENV GEANT4_VERSION=geant4.11.0
ENV ITK_VERSION=v5.4.4

SHELL ["/bin/bash", "-c"]

# Install Miniconda
RUN curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh && \
    bash miniconda.sh -b -p $HOME/miniconda && \
    rm miniconda.sh && \
    $HOME/miniconda/bin/conda create -n opengate_core python=3.11 -y && \
    $HOME/miniconda/bin/conda install -n opengate_core cmake=3.31.2 openssl=3.0.19 aqtinstall -y

ENV PATH="$HOME/miniconda/bin:$PATH"

# Install Homebrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.bash_profile && \
    eval "$(/opt/homebrew/bin/brew shellenv)"

# Ensure brew is usable in all layers
ENV PATH="/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin:$PATH"

# Install Qt6 via brew
RUN brew install qt@6 \
    && brew install --force --verbose --overwrite \
             ccache \
             fftw \
             libomp \
             xquartz \
             xerces-c \
             wget  || true

ENV CMAKE_PREFIX_PATH="/usr/local/opt/qt@6"
ENV Qt6_DIR="/usr/local/opt/qt@6/lib/cmake/Qt6"
ENV PATH="/usr/local/opt/qt@6/bin:$PATH"

RUN mkdir -p $HOME/software/

# Install Geant4
RUN mkdir -p $HOME/software/geant4/src $HOME/software/geant4/bin $HOME/software/geant4/data && \
    cd $HOME/software/geant4 && \
    git clone --branch $GEANT4_VERSION https://github.com/Geant4/geant4.git --depth 1 src && \
    cd bin && \
    conda run -n opengate_core cmake -DCMAKE_CXX_FLAGS=-std=c++17 \
          -DGEANT4_INSTALL_DATA=OFF \
          -DGEANT4_INSTALL_DATADIR=$HOME/software/geant4/data \
          -DGEANT4_USE_QT=ON \
          -DGEANT4_USE_OPENGL_X11=ON \
          -DGEANT4_USE_QT_QT6=ON \
          -DGEANT4_USE_SYSTEM_EXPAT=OFF \
          -DGEANT4_BUILD_MULTITHREADED=ON \
          -DGEANT4_USE_GDML=ON \
        ../src && \
    conda run -n opengate_core cmake --build . --config Release

# Install ITK
RUN mkdir -p $HOME/software/itk/src $HOME/software/itk/bin && \
    cd $HOME/software/itk && \
    git clone --branch $ITK_VERSION https://github.com/InsightSoftwareConsortium/ITK.git --depth 1 src && \
    cd bin && \
    conda run -n opengate_core cmake -DCMAKE_CXX_FLAGS=-std=c++17 \
          -DBUILD_TESTING=OFF \
          -DITK_USE_FFTWD=ON \
          -DITK_USE_FFTWF=ON \
          -DITK_USE_SYSTEM_FFTW:BOOL=ON \
        ../src && \
    conda run -n opengate_core cmake --build . --config Release